const projectsData = {
  "blog-website": {
    title: "Blog Website",
    url: "https://www.mlawed.in/",
    type: "Web Application",
    date: "July 2025",
    category: "Full-Stack Development",
    client: "Advocate Khushboo Sehrawat",
    bannerImg: "/project-images/project-img-2.jpg",
    snapshots: [
      "/project-images/blog-website/snapshot-1.jpg",
      "/project-images/blog-website/snapshot-2.jpg",
      "/project-images/blog-website/snapshot-3.jpg",
      "/project-images/blog-website/snapshot-4.jpg",
      "/project-images/blog-website/snapshot-5.jpg",
    ],
    stack: ["Next.js", "Sentry", "Tailwind CSS", "Google Analytics"],
    background:
      "Advocate Khushboo Sehrawat, a law graduate from HNLU'23 currently pursuing LL.M. from TERI SAS, needed a professional platform to showcase her work as an advocate, writer, and legal analyst. Rajsera Labs designed and developed a sophisticated blog website that serves as her digital presence—a space where legal insights, writings, and professional achievements converge. Built with Next.js for optimal performance and SEO, the website features a clean, elegant design that reflects her professional identity. Integrated with Sentry for error monitoring and Google Analytics for insights, the platform provides a seamless reading experience while establishing her authority in the legal domain.",
    clientReview: [
      "At Rajsera, Bharat is very creative and helpful. He takes into consideration all requirements that one may need in the website and cross checks at each level in website building. I look forward to working with him again and would highly recommend to others as well.",
    ],
    nextProject: {
      title: "Fluortronix App",
      url: "https://www.fluortronix.com/",
      type: "Mobile Application",
      date: "July 2024",
      category: "IoT, Mobile App",
      client: "Fluortronix Innovations Pvt. Ltd",
      slug: "iot-app",
    },
  },
  "iot-app": {
    title: "Fluortronix App",
    url: "https://www.fluortronix.com/",
    type: "Mobile Application",
    date: "July 2025 - Ongoing",
    category: "IoT, Mobile App",
    client: "Fluortronix Innovations Pvt. Ltd",
    bannerImg: "/project-images/project-img-1.jpg",
    snapshots: [
      "/project-images/iot-app/snapshot-1.jpg",
      "/project-images/iot-app/snapshot-2.jpg",
      "/project-images/iot-app/snapshot-3.jpg",
      "/project-images/iot-app/snapshot-4.jpg",
      "/project-images/iot-app/snapshot-5.jpg",
    ],
    stack: ["Kotlin", "Jetpack Compose", "ESP8266", "Room Database", "Retrofit", "Hilt", "Apache POI"],
    background:
      "Fluortronix Innovations challenged Rajsera Labs to create a comprehensive smart lighting solution for agricultural and spectral control applications. The project required seamless integration between ESP8266-based hardware controllers and an Android mobile app with 6 independent PWM channels. Built with Kotlin and Jetpack Compose following Clean Architecture principles, the app features real-time device control, automated scheduling with device auto-sync, spectral data analysis from Excel files, and room-based device organization. The solution enables precise control over grow lights with automated routines, intelligent device provisioning, and sophisticated spectral visualization powered by Vico charts. Every feature was engineered to provide intuitive control while handling complex IoT communication protocols.",
    clientReview: [
      "Rajsera Labs took our complex IoT vision and turned it into a production-ready system that exceeded expectations. Their expertise in both embedded systems and modern Android development was crucial. The seamless integration between our ESP8266 hardware and the mobile app is flawless—the real-time PWM control and automated routine synchronization work beautifully.",
      "The app's ability to analyze spectral data from Excel files and manage multiple devices across rooms has transformed how our clients control their grow light systems. The Material Design 3 interface is intuitive, and the automated device provisioning makes setup effortless. This isn't just an app—it's a complete smart lighting ecosystem that gives us a significant competitive advantage in the agricultural IoT market.",
    ],
    nextProject: {
      title: "Moglix Website & Mobile App",
      url: "https://www.moglix.com/",
      type: "B2B E-Commerce Platform",
      date: "January 2024 - Ongoing",
      category: "E-Commerce, Enterprise, Mobile",
      client: "MOGLI LABS PRIVATE LIMITED",
      slug: "ecommerce-platform",
    },
  },
  "ecommerce-platform": {
    title: "Moglix Website & Mobile App",
    url: "https://www.moglix.com/",
    type: "B2B E-Commerce Platform",
    date: "January 2025 - Ongoing",
    category: "E-Commerce, Enterprise, Mobile",
    client: "MOGLI LABS PRIVATE LIMITED",
    bannerImg: "/project-images/project-img-3.jpg",
    snapshots: [
      "/project-images/ecommerce-platform/snapshot-1.jpg",
      "/project-images/ecommerce-platform/snapshot-2.jpg",
      "/project-images/ecommerce-platform/snapshot-3.jpg",
      "/project-images/ecommerce-platform/snapshot-4.jpg",
      "/project-images/ecommerce-platform/snapshot-5.jpg",
    ],
    stack: ["React", "Next.js", "Node.js", "React Native", "Microservices", "AWS", "MongoDB", "Redis"],
    background:
      "Moglix, India's leading B2B industrial supplies marketplace, partnered with Rajsera Labs to enhance their enterprise e-commerce platform and mobile applications. The collaboration focused on optimizing their digital infrastructure to handle millions of SKUs, enterprise-grade procurement workflows, and complex supply chain integrations. Working alongside Moglix's engineering team, we contributed to developing scalable features for bulk ordering, real-time inventory management, advanced search and filtering, vendor management systems, and seamless B2B payment integrations. The platform needed to serve thousands of enterprise clients with sophisticated procurement needs while maintaining lightning-fast performance and reliability. Built with modern microservices architecture, the solution ensures scalability and resilience for India's growing industrial commerce ecosystem.",
    clientReview: [
      "Collaborating with Rajsera Labs has been instrumental in advancing our platform capabilities. Their team seamlessly integrated with ours, bringing fresh perspectives and technical expertise that elevated our development velocity. Their understanding of B2B e-commerce complexities and ability to deliver production-ready code under tight deadlines has been impressive.",
      "The features they contributed—from optimizing our search algorithms to enhancing our mobile app performance—have directly impacted our user experience metrics. Their commitment to code quality, thorough testing, and collaborative approach made them a valuable extension of our engineering team. We look forward to continued collaboration as we scale our platform to serve India's industrial sector.",
    ],
    nextProject: {
      title: "Blog Website",
      url: "https://www.mlawed.in/",
      type: "Web Application",
      date: "July 2025",
      category: "Full-Stack Development",
      client: "Advocate Khushboo Sehrawat",
      slug: "blog-website",
    },
  },
  "mobile-fitness-app": {
    title: "Mobile Fitness App",
    url: "fitness.example.com",
    type: "Mobile App",
    date: "June 2024",
    category: "Mobile, AR, Health",
    client: "FitTech Solutions",
    bannerImg: "/project-images/project-img-4.jpg",
    snapshots: [
      "/project-images/mobile-fitness-app/snapshot-1.jpg",
      "/project-images/mobile-fitness-app/snapshot-2.jpg",
      "/project-images/mobile-fitness-app/snapshot-3.jpg",
      "/project-images/mobile-fitness-app/snapshot-4.jpg",
      "/project-images/mobile-fitness-app/snapshot-5.jpg",
    ],
    stack: ["React Native", "ARKit", "HealthKit", "Firebase", "TensorFlow", "Stripe"],
    background:
      "FitTech Solutions wanted to revolutionize home workouts with AR technology. Rajsera Labs developed a cross-platform mobile app that uses augmented reality to provide real-time workout guidance and form correction. The app features personalized training plans powered by machine learning, nutrition tracking, social challenges, and seamless payment integration for premium features. Every aspect was optimized for performance and battery efficiency.",
    clientReview: [
      "Rajsera Labs brought our ambitious vision to life with technical excellence. The AR workout guidance is incredibly accurate, and the app performance is flawless on both iOS and Android. They navigated complex challenges like real-time pose detection and cross-platform compatibility with ease.",
      "Since launch, we've seen over 100,000 downloads and a 4.8-star rating. User engagement exceeds our projections by 200%. Rajsera didn't just build an app—they built a fitness revolution. Their attention to UX and technical detail sets them apart from any agency we've worked with.",
    ],
    nextProject: {
      title: "Moglix Website & Mobile App",
      url: "https://www.moglix.com/",
      type: "B2B E-Commerce Platform",
      date: "January 2024 - Ongoing",
      category: "E-Commerce, Enterprise, Mobile",
      client: "MOGLI LABS PRIVATE LIMITED",
      slug: "ecommerce-platform",
    },
  },
};

export default projectsData;

