const projectsData = {
  "blog-website": {
    title: "Blog Website",
    url: "https://www.mlawed.in/",
    type: "Web Application",
    date: "July 2025",
    category: "Full-Stack Development",
    client: "Advocate Khushboo Sehrawat",
    bannerImg: "/project-images/project-img-2.jpg",
    snapshots: [
      "/project-images/blog-website/snapshot-1.jpg",
      "/project-images/blog-website/snapshot-2.jpg",
      "/project-images/blog-website/snapshot-3.jpg",
      "/project-images/blog-website/snapshot-4.jpg",
      "/project-images/blog-website/snapshot-5.jpg",
    ],
    stack: ["Next.js", "Sentry", "Tailwind CSS", "Google Analytics"],
    background:
      "Advocate Khushboo Sehrawat, a law graduate from HNLU'23 currently pursuing LL.M. from TERI SAS, needed a professional platform to showcase her work as an advocate, writer, and legal analyst. Rajsera Labs designed and developed a sophisticated blog website that serves as her digital presence—a space where legal insights, writings, and professional achievements converge. Built with Next.js for optimal performance and SEO, the website features a clean, elegant design that reflects her professional identity. Integrated with Sentry for error monitoring and Google Analytics for insights, the platform provides a seamless reading experience while establishing her authority in the legal domain.",
    clientReview: [
      "At Rajsera, Bharat is very creative and helpful. He takes into consideration all requirements that one may need in the website and cross checks at each level in website building. I look forward to working with him again and would highly recommend to others as well.",
    ],
    nextProject: {
      title: "Fluortronix App",
      url: "https://www.fluortronix.com/",
      type: "Mobile Application",
      date: "July 2024",
      category: "IoT, Mobile App",
      client: "Fluortronix Innovations Pvt. Ltd",
      slug: "iot-app",
    },
  },
  "iot-app": {
    title: "Fluortronix App",
    url: "https://www.fluortronix.com/",
    type: "Mobile Application",
    date: "July 2025 - Ongoing",
    category: "IoT, Mobile App",
    client: "Fluortronix Innovations Pvt. Ltd",
    bannerImg: "/project-images/project-img-1.jpg",
    snapshots: [
      "/project-images/iot-app/snapshot-1.jpg",
      "/project-images/iot-app/snapshot-2.jpg",
      "/project-images/iot-app/snapshot-3.jpg",
      "/project-images/iot-app/snapshot-4.jpg",
      "/project-images/iot-app/snapshot-5.jpg",
    ],
    stack: ["Kotlin", "Jetpack Compose", "ESP8266", "Room Database", "Retrofit", "Hilt", "Apache POI"],
    background:
      "Fluortronix Innovations challenged Rajsera Labs to create a comprehensive smart lighting solution for agricultural and spectral control applications. The project required seamless integration between ESP8266-based hardware controllers and an Android mobile app with 6 independent PWM channels. Built with Kotlin and Jetpack Compose following Clean Architecture principles, the app features real-time device control, automated scheduling with device auto-sync, spectral data analysis from Excel files, and room-based device organization. The solution enables precise control over grow lights with automated routines, intelligent device provisioning, and sophisticated spectral visualization powered by Vico charts. Every feature was engineered to provide intuitive control while handling complex IoT communication protocols.",
    clientReview: [
      "Rajsera Labs took our complex IoT vision and turned it into a production-ready system that exceeded expectations. Their expertise in both embedded systems and modern Android development was crucial. The seamless integration between our ESP8266 hardware and the mobile app is flawless—the real-time PWM control and automated routine synchronization work beautifully.",
      "The app's ability to analyze spectral data from Excel files and manage multiple devices across rooms has transformed how our clients control their grow light systems. The Material Design 3 interface is intuitive, and the automated device provisioning makes setup effortless. This isn't just an app—it's a complete smart lighting ecosystem that gives us a significant competitive advantage in the agricultural IoT market.",
    ],
    nextProject: {
      title: "Moglix Website & Mobile App",
      url: "https://www.moglix.com/",
      type: "B2B E-Commerce Platform",
      date: "January 2024 - Ongoing",
      category: "E-Commerce, Enterprise, Mobile",
      client: "MOGLI LABS PRIVATE LIMITED",
      slug: "ecommerce-platform",
    },
  },
  "ecommerce-platform": {
    title: "Moglix Website & Mobile App",
    url: "https://www.moglix.com/",
    type: "B2B E-Commerce Platform",
    date: "January 2025 - Ongoing",
    category: "E-Commerce, Enterprise, Mobile",
    client: "MOGLI LABS PRIVATE LIMITED",
    bannerImg: "/project-images/project-img-3.jpg",
    snapshots: [
      "/project-images/ecommerce-platform/snapshot-1.jpg",
      "/project-images/ecommerce-platform/snapshot-2.jpg",
      "/project-images/ecommerce-platform/snapshot-3.jpg",
      "/project-images/ecommerce-platform/snapshot-4.jpg",
      "/project-images/ecommerce-platform/snapshot-5.jpg",
    ],
    stack: ["React", "Next.js", "Node.js", "React Native", "Microservices", "AWS", "MongoDB", "Redis"],
    background:
      "Moglix, India's leading B2B industrial supplies marketplace, partnered with Rajsera Labs to enhance their enterprise e-commerce platform and mobile applications. The collaboration focused on optimizing their digital infrastructure to handle millions of SKUs, enterprise-grade procurement workflows, and complex supply chain integrations. Working alongside Moglix's engineering team, we contributed to developing scalable features for bulk ordering, real-time inventory management, advanced search and filtering, vendor management systems, and seamless B2B payment integrations. The platform needed to serve thousands of enterprise clients with sophisticated procurement needs while maintaining lightning-fast performance and reliability. Built with modern microservices architecture, the solution ensures scalability and resilience for India's growing industrial commerce ecosystem.",
    clientReview: [
      "Collaborating with Rajsera Labs has been instrumental in advancing our platform capabilities. Their team seamlessly integrated with ours, bringing fresh perspectives and technical expertise that elevated our development velocity. Their understanding of B2B e-commerce complexities and ability to deliver production-ready code under tight deadlines has been impressive.",
      "The features they contributed—from optimizing our search algorithms to enhancing our mobile app performance—have directly impacted our user experience metrics. Their commitment to code quality, thorough testing, and collaborative approach made them a valuable extension of our engineering team. We look forward to continued collaboration as we scale our platform to serve India's industrial sector.",
    ],
    nextProject: {
      title: "Blog Website",
      url: "https://www.mlawed.in/",
      type: "Web Application",
      date: "July 2025",
      category: "Full-Stack Development",
      client: "Advocate Khushboo Sehrawat",
      slug: "blog-website",
    },
  },
  "luxbubble-app": {
    title: "LuxBubble Beauty Services",
    url: "https://apps.apple.com/us/app/luxbubble/id1620827707",
    type: "Mobile Application",
    date: "March 2024",
    category: "Marketplace, Beauty Services, Mobile",
    client: "Supersys Consulting Pty Ltd",
    bannerImg: "/project-images/project-img-5.jpg",
    snapshots: [
      "/project-images/luxbubble-app/snapshot-1.png",
      "/project-images/luxbubble-app/snapshot-2.png",
      "/project-images/luxbubble-app/snapshot-3.png",
      "/project-images/luxbubble-app/snapshot-4.png",
      "/project-images/luxbubble-app/snapshot-5.png",
    ],
    stack: ["React Native", "Node.js", "AWS", "MongoDB", "Stripe", "Google Maps API", "Firebase"],
    background:
      "LuxBubble is an innovative online beauty services marketplace that revolutionizes how users book hair styling, makeup, and other beauty services from their mobile devices. Developed for Supersys Consulting Pty Ltd, the platform consists of three interconnected mobile applications: LuxBubble (for customers), LuxBubble Provider (for service providers), and LuxBubble Staff (for staff management). The ecosystem enables seamless connections between beauty professionals and clients based on location, services, gender preferences, and real-time availability. Service providers can create profiles, add services with pricing, manage staff schedules, and process instant pre-payments through Stripe integration. Customers can browse providers by category, choose between Mobile or Salon services, filter by distance and gender, book appointments, chat with providers, and rate their experiences. The platform features sophisticated geo-location tracking, real-time booking notifications, comprehensive profile management, and intelligent sorting by popularity, price, and recency. Built with React Native for cross-platform compatibility and Node.js backend with MongoDB, the solution ensures scalability while delivering a smooth booking experience for Australia's beauty services industry.",
    clientReview: [
      "Working with Rajsera Labs transformed our vision for LuxBubble into a powerful reality. They developed three seamlessly integrated mobile applications that work together flawlessly—the customer app, provider app, and staff app. The real-time booking system, geo-location features, and Stripe payment integration work beautifully across all platforms.",
      "The attention to detail in user experience is remarkable. Features like filtering by distance and gender, the chat functionality, and the review system have made LuxBubble incredibly popular among both beauty professionals and customers. The app handles complex scenarios like real-time availability, staff scheduling, and mobile vs salon bookings with ease. Rajsera Labs delivered a complete marketplace solution that's driving our business growth in the competitive beauty services market.",
    ],
    nextProject: {
      title: "Celloux Crypto Trading Platform",
      url: "https://play.google.com/store/apps/details?id=com.coinwells",
      type: "Cryptocurrency Exchange",
      date: "August 2024",
      category: "FinTech, Blockchain, Cryptocurrency",
      client: "Celloux Technologies",
      slug: "celloux-crypto-platform",
    },
  },
  "celloux-crypto-platform": {
    title: "Celloux Crypto Trading Platform",
    url: "https://play.google.com/store/apps/details?id=com.coinwells",
    type: "Cryptocurrency Exchange",
    date: "August 2024 - Ongoing",
    category: "FinTech, Blockchain, Cryptocurrency",
    client: "Celloux Technologies",
    bannerImg: "/project-images/project-img-6.jpg",
    snapshots: [
      "/project-images/celloux-crypto-platform/snapshot-1.png",
      "/project-images/celloux-crypto-platform/snapshot-2.png",
      "/project-images/celloux-crypto-platform/snapshot-3.png",
      "/project-images/celloux-crypto-platform/snapshot-4.png",
      "/project-images/celloux-crypto-platform/snapshot-5.png",
    ],
    stack: ["Swift", "Kotlin", "React Native", "Node.js", "MongoDB", "Blockchain", "Web3", "Redis"],
    background:
      "Celloux approached Rajsera Labs with an ambitious vision to create a secure and user-friendly cryptocurrency trading platform that would make digital asset trading accessible to both novice and experienced traders. We developed a comprehensive solution consisting of native iOS (Swift) and Android (Kotlin) applications, a responsive web platform built with React, and a powerful Node.js backend infrastructure. The platform enables users to trade multiple cryptocurrencies with real-time conversion rates, featuring blockchain-based transactions with complete transparency and security. Key features include user authorization with multi-factor authentication, support for multiple cryptocurrencies, push notifications for price alerts and transaction confirmations, QR code scanner for wallet addresses, blockchain confirmations tracking, coin merge transactions, seamless deposit and withdrawal of both crypto and fiat currencies, and national currency support for trading pairs. The admin panel provides comprehensive oversight of all platform operations, user management, and transaction monitoring. Built with unbreachable security standards, the platform implements advanced encryption, secure wallet management, and regulatory compliance measures. The solution has empowered Celloux to scale their cryptocurrency trading business, attract a wider user base, and generate higher revenue through a seamless, secure, and intuitive trading experience across all platforms.",
    clientReview: [
      "Rajsera Labs transformed our cryptocurrency trading vision into a production-ready platform that exceeded all expectations. They delivered native iOS and Android apps, a responsive website, and a comprehensive admin panel—all working in perfect harmony. The security implementations are top-notch, with blockchain-based transactions, multi-factor authentication, and secure wallet management.",
      "The platform's ease of use combined with enterprise-grade security has been a game-changer for our business. Users love the intuitive interface, real-time conversion rates, and seamless deposit/withdrawal experience. The QR code scanner and push notifications enhance usability significantly. Since launch, we've seen tremendous user growth and engagement. Rajsera Labs didn't just build a crypto trading app—they built a secure financial ecosystem that positions us as a leader in the cryptocurrency exchange market.",
    ],
    nextProject: {
      title: "Fluortronix App",
      url: "https://www.fluortronix.com/",
      type: "Mobile Application",
      date: "July 2024",
      category: "IoT, Mobile App",
      client: "Fluortronix Innovations Pvt. Ltd",
      slug: "iot-app",
    },
  },
  "mobile-fitness-app": {
    title: "Mobile Fitness App",
    url: "fitness.example.com",
    type: "Mobile App",
    date: "June 2024",
    category: "Mobile, AR, Health",
    client: "FitTech Solutions",
    bannerImg: "/project-images/project-img-6.jpg",
    snapshots: [
      "/project-images/mobile-fitness-app/snapshot-1.jpg",
      "/project-images/mobile-fitness-app/snapshot-2.jpg",
      "/project-images/mobile-fitness-app/snapshot-3.jpg",
      "/project-images/mobile-fitness-app/snapshot-4.jpg",
      "/project-images/mobile-fitness-app/snapshot-5.jpg",
    ],
    stack: ["React Native", "ARKit", "HealthKit", "Firebase", "TensorFlow", "Stripe"],
    background:
      "FitTech Solutions wanted to revolutionize home workouts with AR technology. Rajsera Labs developed a cross-platform mobile app that uses augmented reality to provide real-time workout guidance and form correction. The app features personalized training plans powered by machine learning, nutrition tracking, social challenges, and seamless payment integration for premium features. Every aspect was optimized for performance and battery efficiency.",
    clientReview: [
      "Rajsera Labs brought our ambitious vision to life with technical excellence. The AR workout guidance is incredibly accurate, and the app performance is flawless on both iOS and Android. They navigated complex challenges like real-time pose detection and cross-platform compatibility with ease.",
      "Since launch, we've seen over 100,000 downloads and a 4.8-star rating. User engagement exceeds our projections by 200%. Rajsera didn't just build an app—they built a fitness revolution. Their attention to UX and technical detail sets them apart from any agency we've worked with.",
    ],
    nextProject: {
      title: "Moglix Website & Mobile App",
      url: "https://www.moglix.com/",
      type: "B2B E-Commerce Platform",
      date: "January 2024 - Ongoing",
      category: "E-Commerce, Enterprise, Mobile",
      client: "MOGLI LABS PRIVATE LIMITED",
      slug: "ecommerce-platform",
    },
  },
};

export default projectsData;

